theme: jekyll-theme-minimal
title: Brodo Luca
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/luca-brodo-5a752b192/">LinkedIn</a> |
  <a href="https://github.com/brodoluca">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing a MEng degree in Embedded Systems Engineering at FH Dortmund.
  <br><br>
  I am currently a Machine Learning Research Assistant at Hochschule Hamm-Lippstadt with a focus on Deep Learning research.
  <br><br>
  </p>
